### PR TITLE
Upgrade vulnerable dependencies

### PR DESCRIPTION
**Pull request by masihyeganeh**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/208)

### CODE REVIEW

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/208)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`contract/Cargo.toml` line 39 at r1](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/208#-NwJ3svx9_OnrQ7T4P08:-NwJ3svx9_OnrQ7T4P09:b-ncritg) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/889359525e37ea4fa0602cb4ddc41da8eb6b74f7/contract/Cargo.toml#L39)):*
> ```TOML
> sha2 = "0.10.8"
> thiserror = "1.0.56"
> libsecp256k1 = "0.5.0"
> ```

I'm not sure if adding new version of the transitive dependencies is going to make any difference here, but I can't find a good way to actually replace them. I'm aware of "patch"ing, but it seems that there is no standard way to upgrade them:
https://github.com/rust-lang/cargo/issues/5640

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/208)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @keyleu, @miladz68, @wojtek-coreum, and @ysv)

___
*[`contract/Cargo.toml` line 39 at r1](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/208#-NwJ3svx9_OnrQ7T4P08:-NwJ6W_i7NpwCSt0--A-:b8yibb3) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/889359525e37ea4fa0602cb4ddc41da8eb6b74f7/contract/Cargo.toml#L39)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

I'm not sure if adding new version of the transitive dependencies is going to make any difference here, but I can't find a good way to actually replace them. I'm aware of "patch"ing, but it seems that there is no standard way to upgrade them:
https://github.com/rust-lang/cargo/issues/5640
</blockquote></details>

@keyleu  WDYT ?

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/208)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`contract/Cargo.toml` line 39 at r1](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/208#-NwJ3svx9_OnrQ7T4P08:-NwJDU5S80eQv28XqEcj:bb16t6j) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/889359525e37ea4fa0602cb4ddc41da8eb6b74f7/contract/Cargo.toml#L39)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

@keyleu  WDYT ?
</blockquote></details>

I don't think this is going to make any difference. The only "important" one even though we are also not affected is the cosmwasm-std one. I think we can remove the rest.

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/208)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by keyleu — DISMISSED** [review]
> Reviewed 5 of 7 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/208)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by miladz68 — DISMISSED** [review]
> Reviewed 5 of 7 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/208)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by miladz68 — DISMISSED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/208)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by dzmitryhil — DISMISSED** [review]
> Reviewed 4 of 4 files at r3, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/208)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 4 of 4 files at r3, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/208)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/208)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh and @wojtek-coreum)

___
*[`.DS_Store` line 0 at r6](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/208#-Nwe-z_v5SS0e4o0h0sn:-Nwe-z_v5SS0e4o0h0so:bb847zq) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/857962a95d8926b5e668a48a7768a1e17ee9863e/.DS_Store#L0)):*
ignore ?

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/208)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh and @wojtek-coreum)

___
*[`.DS_Store` line  at r6](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/208#-Nwe-z_v5SS0e4o0h0sn:-Nwe03jdEFdUukDJiRQe:b-awitor) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/857962a95d8926b5e668a48a7768a1e17ee9863e/.DS_Store#L)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

ignore ?
</blockquote></details>

eventually we had a rule that we add only project-specific files to .gitignore e.g wasm binaries etc
But global things which are dependent on system etc we prefer everyone to have .gitignore_global and put there any files specific for their system etc

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 1 of 7 files at r7.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/208)* status: 5 of 11 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`.DS_Store` line  at r6](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/208#-Nwe-z_v5SS0e4o0h0sn:-NweV1mx65omJYHhlclN:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/857962a95d8926b5e668a48a7768a1e17ee9863e/.DS_Store#L)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

eventually we had a rule that we add only project-specific files to .gitignore e.g wasm binaries etc
But global things which are dependent on system etc we prefer everyone to have .gitignore_global and put there any files specific for their system etc
</blockquote></details>

Done.

**Review by ysv — DISMISSED** [review]
> Reviewed 2 of 7 files at r7, 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/208)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Review by ysv — DISMISSED** [review]
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/208)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, 1 of 7 files at r7, 5 of 7 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/208)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 7 files at r7, 5 of 7 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/208)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Review by ysv — APPROVED** [review]
> Reviewed 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/208)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> Reviewed 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/208)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Pull request merged**
