### PR TITLE
Add RPC client clawback test

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

Add RPC client clawback test

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/193)

### CODE REVIEW

**Review by miladz68 — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/193)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/193)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

___
*[`integration-tests/xrpl/rpc_test.go` line 970 at r1](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/193#-Nt0lwX31yqKSHcQGdsT:-Nt0lwX31yqKSHcQGdsU:b-bdzt3f) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/a9ab1b7c314e108fa81d4b53097e03148837b931/integration-tests/xrpl/rpc_test.go#L970)):*
> ```Go
> 		// https://xrpl.org/docs/references/protocol/transactions/types/accountset/#accountset-flags
> 		// asfAllowTrustLineClawback	16
> 		SetFlag: lo.ToPtr(uint32(16)),
> ```

set const for this

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/193)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

___
*[`integration-tests/xrpl/rpc_test.go` line 970 at r1](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/193#-Nt0lwX31yqKSHcQGdsT:-Nt0s2bs7LM69nk8f0S3:be0axhl) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/a9ab1b7c314e108fa81d4b53097e03148837b931/integration-tests/xrpl/rpc_test.go#L970)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

set const for this
</blockquote></details>

Make sense, done.

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/193)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/193)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
