### PR TITLE
New build system

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/210)

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/210)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`Makefile` line 27 at r1](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/210#-O-ALu7S0qWtImhEb1ql:-O-ALu7S0qWtImhEb1qm:bkv5b8u) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/dd3267987cdcaf2fef6c8638820208f2df6d60cb/Makefile#L27)):*
> ```Makefile
> .PHONY: znet-start
> znet-start:
> 	$(BUILDER) znet start --profiles=bridge-xrpl
> ```

I think it makes sense to allow profiles to be passed as arg

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/210)* status: 12 of 16 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @masihyeganeh, @miladz68, and @ysv)

___
*[`Makefile` line 27 at r1](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/210#-O-ALu7S0qWtImhEb1ql:-O-ANGqY062B8uWfgJof:b-a7k0tf) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/dd3267987cdcaf2fef6c8638820208f2df6d60cb/Makefile#L27)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think it makes sense to allow profiles to be passed as arg
</blockquote></details>

makefiles don't support args, only variables which is horrible

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/210)* status: 9 of 39 files reviewed, 2 unresolved discussions (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`relayer/cmd/cli/cli.go` line 30 at r4](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/210#-O-L1tWn4kBYoNbZOHQg:-O-L1tWn4kBYoNbZOHQh:b-f85q38) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/490ce762b442cf955082b55cfe0f6171046320f7/relayer/cmd/cli/cli.go#L30)):*
> ```Go
> )
> 
> //go:generate ../../../bin/mockgen -destination=cli_mocks_test.go -package=cli_test . BridgeClient,Runner
> ```

Can we add `mockgen` to the PATH in the makefile and use just `mockgen` here?

**Review by masihyeganeh — CHANGES_REQUESTED** [review]
> Reviewed 9 of 16 files at r1, 1 of 9 files at r2, 24 of 25 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/210)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`build/go.mod` line 40 at r4](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/210#-O-L0zlD98dgCwLKYSAh:-O-L0zlD98dgCwLKYSAi:bon4z08) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/490ce762b442cf955082b55cfe0f6171046320f7/build/go.mod#L40)):*
> ```XML
> 
> require (
> 	cloud.google.com/go v0.112.0 // indirect
> ```

Was the project using these dependencies before?
Or this much dependencies are added just because of new build system?

**Review by miladz68 — DISMISSED** [review]
> Reviewed 1 of 9 files at r2, 24 of 25 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/210)* status: all files reviewed, 2 unresolved discussions (waiting on @wojtek-coreum and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/210)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, and @ysv)

___
*[`build/go.mod` line 40 at r4](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/210#-O-L0zlD98dgCwLKYSAh:-O-L5wPX-p0hsmMDqdvZ:b3x2loj) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/490ce762b442cf955082b55cfe0f6171046320f7/build/go.mod#L40)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Was the project using these dependencies before?
Or this much dependencies are added just because of new build system?
</blockquote></details>

I guess it's because of imported coreum builder
___
*[`relayer/cmd/cli/cli.go` line 30 at r4](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/210#-O-L1tWn4kBYoNbZOHQg:-O-L7mGyCxNaZvF8StWY:b5c17j8) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/490ce762b442cf955082b55cfe0f6171046320f7/relayer/cmd/cli/cli.go#L30)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Can we add `mockgen` to the PATH in the makefile and use just `mockgen` here?
</blockquote></details>

Good idea! Implemented here: https://reviewable.io/reviews/CoreumFoundation/crust/416

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> Reviewed 9 of 16 files at r1, 1 of 9 files at r2, 24 of 25 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/210)* status: all files reviewed, 2 unresolved discussions (waiting on @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`relayer/cmd/cli/cli.go` line 30 at r4](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/210#-O-L1tWn4kBYoNbZOHQg:-O-L84ZaDkE9yL6oUXsm:b-kztic5) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/490ce762b442cf955082b55cfe0f6171046320f7/relayer/cmd/cli/cli.go#L30)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Good idea! Implemented here: https://reviewable.io/reviews/CoreumFoundation/crust/416
</blockquote></details>

The reference PR is approved. Waiting the changes here.

**Review by masihyeganeh — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/210)* status: all files reviewed, 2 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`build/go.mod` line 40 at r4](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/210#-O-L0zlD98dgCwLKYSAh:-O-LKvgu9sHKbtoJ2aG0:bjntlzb) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/490ce762b442cf955082b55cfe0f6171046320f7/build/go.mod#L40)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I guess it's because of imported coreum builder
</blockquote></details>

So, now we are downloading and building 100 more dependencies for no good reason?

**Review by masihyeganeh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/210)* status: all files reviewed, 2 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`build/go.mod` line 40 at r4](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/210#-O-L0zlD98dgCwLKYSAh:-O-LMgk-AKaLykqLLNzq:b-biyqv5) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/490ce762b442cf955082b55cfe0f6171046320f7/build/go.mod#L40)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Be did it before anyway because `cored` has been built anyway - just by the other builder
</blockquote></details>

How about binary size? can you compare it between two versions?
I marked my messages as non-blocking, but I'm not satisfied with this change

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/210)* status: all files reviewed, 2 unresolved discussions (waiting on @wojtek-coreum and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/210)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil and @ysv)

___
*[`relayer/cmd/cli/cli.go` line 30 at r4](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/210#-O-L1tWn4kBYoNbZOHQg:-O-LQnlIACtbdBaLn88L:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/490ce762b442cf955082b55cfe0f6171046320f7/relayer/cmd/cli/cli.go#L30)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The reference PR is approved. Waiting the changes here.
</blockquote></details>

Done.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/210)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, and @ysv)

___
*[`build/go.mod` line 40 at r4](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/210#-O-L0zlD98dgCwLKYSAh:-O-LQsLA4ClK8_9TkxTr:bt12zh5) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/490ce762b442cf955082b55cfe0f6171046320f7/build/go.mod#L40)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

How about binary size? can you compare it between two versions?
I marked my messages as non-blocking, but I'm not satisfied with this change
</blockquote></details>

but why do we care? The total size is reduced for sure, because before we used two binaries, now we use one.

**Review by masihyeganeh — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/210)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

**Review by miladz68 — DISMISSED** [review]
> Reviewed 7 of 7 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/210)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/210)* status: 33 of 41 files reviewed, all discussions resolved (waiting on @masihyeganeh, @miladz68, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 5 of 7 files at r5, 6 of 9 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/210)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh, @miladz68, and @ysv)

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 7 of 9 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/210)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`bin/coreumbridge-xrpl-builder` line 16 at r8](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/210#-O-jxIlf2xaz9nLccsEj:-O-jxIlg0wS0_eZN-LXz:b-h5ux3w) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/fbeae60e635aa8d5357811c40454723852a1253a/bin/coreumbridge-xrpl-builder#L16)):*
> ```
> 
>   pushd build > /dev/null
>   GOVCS='public:git|hg|bzr' go build -trimpath -o "$BUILD_BIN" ./cmd/builder
> ```

Do all our users still need to have the bazaar client?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/210)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @miladz68, and @ysv)

___
*[`bin/coreumbridge-xrpl-builder` line 16 at r8](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/210#-O-jxIlf2xaz9nLccsEj:-O-kChgl6GwJQ1iJdeL3:b2nhswy) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/fbeae60e635aa8d5357811c40454723852a1253a/bin/coreumbridge-xrpl-builder#L16)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Do all our users still need to have the bazaar client?
</blockquote></details>

Yes

**Pull request merged**
