### PR TITLE
Build system

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/163)

### CODE REVIEW

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/163)* status: 19 of 27 files reviewed, 7 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`.github/workflows/relayer-ci.yml` line 25 at r2](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/163#-Nsw0ppq8JYuDV5UKgcc:-Nt-voVsCjTilYu1cZIN:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/d472ca68b7ada46d9bad607488831021b753e762/.github/workflows/relayer-ci.yml#L25)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do you need the `go-cache` flag if it always true ?
</blockquote></details>

Done.
___
*[`.github/workflows/relayer-ci.yml` line 120 at r2](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/163#-Nsw0fft5BnWHVKZ-aNW:-Nt-vtte1a9HxB7tgKK1:b86kt9l) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/d472ca68b7ada46d9bad607488831021b753e762/.github/workflows/relayer-ci.yml#L120)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We don't need to cache the wasm since we cache the crust fully.
</blockquote></details>

this line excludes the file from cache
___
*[`build/bridge/contract.go` line 31 at r1](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/163#-NsSyVjz1M_cHiLd7gZk:-Nt-zXvd81rf-OULlsad:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/2cd8a655da4cd44eee017bdcf7a34219900d4612/build/bridge/contract.go#L31)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But you already use the `rust.BuildSmartContact`, why not to move it now?
</blockquote></details>

Done.
___
*[`build/bridge/image/Dockerfile.tmpl` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/163#-Nsw15O-9Dy0r4oKzEwS:-Nt-zjua9_ncoZ-1vOik:buar8oi) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/d472ca68b7ada46d9bad607488831021b753e762/build/bridge/image/Dockerfile.tmpl#L1)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What do we do with the Dockerfile which is in the relayer root? If you plan to remove it later let's have a task or FIXME to do it.
</blockquote></details>

it will be removed when I update the Makefile

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/163)* status: 13 of 27 files reviewed, 3 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/relayer-ci.yml` line 120 at r2](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/163#-Nsw0fft5BnWHVKZ-aNW:-Nt0l_8ZAB1vM6XXrdp2:b-9i8hqc) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/d472ca68b7ada46d9bad607488831021b753e762/.github/workflows/relayer-ci.yml#L120)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

this line excludes the file from cache
</blockquote></details>

This part? So probably it should be in the crust cache then?

**Review by ysv — APPROVED** [review]
> Reviewed 8 of 8 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/163)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

**Review by ysv — APPROVED** [review]
> Reviewed 15 of 15 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/163)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/163)* status: 21 of 29 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`.github/workflows/relayer-ci.yml` line 44 at r1](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/163#-NsSxVqO4QOX_1zezRsk:-Nuh5WnTA85HQBHUyZt2:bb0og8j) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/2cd8a655da4cd44eee017bdcf7a34219900d4612/.github/workflows/relayer-ci.yml#L44)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This part is still not addressed.
</blockquote></details>

Now we download all the dependencies before forking jobs, so cache should work
___
*[`build/index.go` line 24 at r2](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/163#-Nsw1Ykc6ksD3bus2iom:-Nuh5VJA8dbPR6y__yQc:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/d472ca68b7ada46d9bad607488831021b753e762/build/index.go#L24)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Taking into account that we build everything in the CI, IMO we don't need separate `build` for each test backage.
</blockquote></details>

Done.

**Review by ysv — APPROVED** [review]
> Reviewed 6 of 8 files at r5, 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/163)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/163)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil and @miladz68)

___
*[`.github/workflows/relayer-ci.yml` line 34 at r6](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/163#-Nuy11FdBiGrKyS6KUNQ:-Nv0WB2Z5sHYbhAoe2Oy:b-mma5qr) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/f5d944edabb29f57f895bfc074f933d4f4a4304a/.github/workflows/relayer-ci.yml#L34)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Let's move the call of the all builders and znet to makefile instead. We already have `build-dev-env` command which does exactly this
</blockquote></details>

No, this is the makefile which will call the builders. And CI calls the builder too
___
*[`.github/workflows/relayer-ci.yml` line 37 at r6](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/163#-Nuy1Fsj7QnN-i2_GNmP:-Nv0WNHWEet9r6TijaS7:bz8icwa) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/f5d944edabb29f57f895bfc074f933d4f4a4304a/.github/workflows/relayer-ci.yml#L37)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do you start and build later?
</blockquote></details>

znet starts the environment and this line runs integration tests on top of that environment. It was decided that integration tests should be run by each repo (not by the znet)
___
*[`build/index.go` line 27 at r6](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/163#-Nuy1e643x-qQRxLsFU1:-Nv0W_ed6aj9vWm_kOYh:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/f5d944edabb29f57f895bfc074f933d4f4a4304a/build/index.go#L27)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Haven't we changed the build to run?
</blockquote></details>

Done.
___
*[`build/index.go` line 36 at r6](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/163#-Nuy1qUe9UwClopjsUd8:-Nv0Wcw01OZlHqrW2fmC:b226lc) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/f5d944edabb29f57f895bfc074f933d4f4a4304a/build/index.go#L36)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Do you use it in the github CI ? IF not let's add at least task, otherwise it useless.
</blockquote></details>

in next step e will call it from github action like we do for coreum

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/163)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/relayer-ci.yml` line 34 at r6](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/163#-Nuy11FdBiGrKyS6KUNQ:-Nv0yrpE1KZgUBfJf5Uz:b-9fe6kd) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/f5d944edabb29f57f895bfc074f933d4f4a4304a/.github/workflows/relayer-ci.yml#L34)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

No, this is the makefile which will call the builders. And CI calls the builder too
</blockquote></details>

The `build` command here uses multiple sub-command, so to reduce code duplication, it make sense IMO to use makefile to simplify it. Or use additional build command to do it. Also the makefile can set default PATH to `coreumbridge-xrpl-builder` so you won't have to set it up manually. 

@ysv @miladz68 WDYT ?

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/163)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

___
*[`.github/workflows/relayer-ci.yml` line 34 at r6](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/163#-Nuy11FdBiGrKyS6KUNQ:-Nv1Ii-A-JRGOMRndQHY:b-ath1wo) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/f5d944edabb29f57f895bfc074f933d4f4a4304a/.github/workflows/relayer-ci.yml#L34)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The `build` command here uses multiple sub-command, so to reduce code duplication, it make sense IMO to use makefile to simplify it. Or use additional build command to do it. Also the makefile can set default PATH to `coreumbridge-xrpl-builder` so you won't have to set it up manually. 

@ysv @miladz68 WDYT ?
</blockquote></details>

yes, I agree makefile makes sense
In the milistone ticket we have task to add makefiles to probably all repos. 
At least inside coreum it should be as we agree but IMO it makes sense to have it everywhere 

For now I'm ok to either keep it like this or add makefile in this PR

**Review by miladz68 — APPROVED** [review]
> Reviewed 9 of 27 files at r1, 4 of 8 files at r2, 1 of 6 files at r3, 5 of 15 files at r4, 6 of 8 files at r5, 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/163)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil and @wojtek-coreum)

___
*[`.github/workflows/relayer-ci.yml` line 34 at r6](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/163#-Nuy11FdBiGrKyS6KUNQ:-Nv1kAhp9AKKhGysnZun:b-9lfnrn) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/f5d944edabb29f57f895bfc074f933d4f4a4304a/.github/workflows/relayer-ci.yml#L34)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

yes, I agree makefile makes sense
In the milistone ticket we have task to add makefiles to probably all repos. 
At least inside coreum it should be as we agree but IMO it makes sense to have it everywhere 

For now I'm ok to either keep it like this or add makefile in this PR
</blockquote></details>

I agree that Makefile should be interface to interact with the builder.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/163)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/relayer-ci.yml` line 34 at r6](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/163#-Nuy11FdBiGrKyS6KUNQ:-Nv673XwBa3Ce5XX8bM-:b6mp7xg) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/f5d944edabb29f57f895bfc074f933d4f4a4304a/.github/workflows/relayer-ci.yml#L34)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I agree that Makefile should be interface to interact with the builder.
</blockquote></details>

Agreed to do it later.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/163)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/163)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/163)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/163)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Pull request merged**
