### PR TITLE
Update CI cache to  ScribeMD/docker-cache.

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

Update CI cache to  ScribeMD/docker-cache.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/209)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/209)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/xrpl.go` line 195 at r1](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/209#-Nxrj-tR8xSW29R745ZO:-Nxrj-tR8xSW29R745ZP:b6kvc26) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/8c69f23a10f1649fe0d6eb67efc29af0782059a3/integration-tests/xrpl.go#L195)):*
> ```Go
> 	require.NoError(t, c.signer.Sign(&fundXrpTx, faucetKeyringKeyName))
> 
> 	//t.Logf("Funding account, account address: %s, amount: %f", acc, amount)
> ```

shall we remove comments or log lines ?
___
*[`integration-tests/xrpl/matching_test.go` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/209#-NxrjB193WbUABLVdYWR:-NxrjB193WbUABLVdYWS:b-b3h7f0) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/8c69f23a10f1649fe0d6eb67efc29af0782059a3/integration-tests/xrpl/matching_test.go#L1)):*
> ```Go
> //go:build integrationtests
> ```

pls remove this

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/209)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/xrpl.go` line 195 at r1](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/209#-Nxrj-tR8xSW29R745ZO:-NxuigGK5D9V1yiWoJVw:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/8c69f23a10f1649fe0d6eb67efc29af0782059a3/integration-tests/xrpl.go#L195)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

shall we remove comments or log lines ?
</blockquote></details>

Done.
___
*[`integration-tests/xrpl/matching_test.go` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/209#-NxrjB193WbUABLVdYWR:-Nxuigus5ESL1XcQ3qaY:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/8c69f23a10f1649fe0d6eb67efc29af0782059a3/integration-tests/xrpl/matching_test.go#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

pls remove this
</blockquote></details>

Done.

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/209)* status: all files reviewed, 2 unresolved discussions (waiting on @masihyeganeh, @wojtek-coreum, and @ysv)

**Review by ysv — DISMISSED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/209)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh and @wojtek-coreum)

**Review by ysv — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/209)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh, @miladz68, and @wojtek-coreum)

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 2 of 3 files at r2, 1 of 2 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/209)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @wojtek-coreum)

**Pull request merged**
