### PR TITLE
Integrate contract migration

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

Integrate contract migration

* Migrate the contract before the integration tests start
* Add migration integration test
* Add migration CLI and instructions

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/160)

### CODE REVIEW

**Review by ysv — DISMISSED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/160)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Review by miladz68 — DISMISSED** [review]
> Reviewed 2 of 4 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/160)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Review by miladz68 — DISMISSED** [review]
> Reviewed 22 of 22 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/160)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @keyleu, @wojtek-coreum, and @ysv)

**Review by keyleu — APPROVED** [review]
> Reviewed 5 of 25 files at r1, 22 of 22 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/160)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 5 of 25 files at r1, 20 of 22 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/160)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil and @ysv)

___
*[`integration-tests/contract/cancel_pending_operation_test.go` line 37 at r6](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/160#-Nt0oOX-2wwecpSWRJGb:-Nt0oOX-2wwecpSWRJGc:b-rsizua) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/73f26209d4c4492a8d379674597e76a66d6e415f/integration-tests/contract/cancel_pending_operation_test.go#L37)):*
> ```Go
> 	})
> 
> 	owner, contractClient := integrationtests.DeployInstantiateAndMigrateContract(
> ```

do you need to migrate contract in every integration test?
___
*[`integration-tests/processes/env_test.go` line 163 at r6](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/160#-Nt0pTFYBzOcPjb45AqW:-Nt0pTFYBzOcPjb45AqX:bdwhv9s) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/73f26209d4c4492a8d379674597e76a66d6e415f/integration-tests/processes/env_test.go#L163)):*
> ```Go
> 		)
> 		require.NoError(t, err)
> 		require.NoError(t, contractClient.SetContractAddress(contractAddress))
> ```

could you pass contract address using a constructor?
___
*[`relayer/coreum/contract.go` line 586 at r6](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/160#-Nt0pqb-1yuPimV_ru1g:-Nt0pqb-1yuPimV_ru1h:b10gtvs) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/73f26209d4c4492a8d379674597e76a66d6e415f/relayer/coreum/contract.go#L586)):*
> ```Go
> 	byteCode []byte,
> ) (*sdk.TxResponse, uint64, error) {
> 	txRes, codeID, err := c.deployContract(ctx, sender, byteCode)
> ```

Can't you simply put the body of `c.deployContract` here and use the exported method everywhere?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/160)* status: all files reviewed, 3 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`integration-tests/contract/cancel_pending_operation_test.go` line 37 at r6](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/160#-Nt0oOX-2wwecpSWRJGb:-Nt0sMo2BX37ce9LKz1J:bdh3tit) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/73f26209d4c4492a8d379674597e76a66d6e415f/integration-tests/contract/cancel_pending_operation_test.go#L37)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

do you need to migrate contract in every integration test?
</blockquote></details>

To be sure that the new contract is backward compatible - yes. 
___
*[`integration-tests/processes/env_test.go` line 163 at r6](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/160#-Nt0pTFYBzOcPjb45AqW:-Nt0sU5R04lBxpGeF2uh:b-xp01hd) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/73f26209d4c4492a8d379674597e76a66d6e415f/integration-tests/processes/env_test.go#L163)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

could you pass contract address using a constructor?
</blockquote></details>

We deploy the contract and instantiate using the same client. So we don't have the address at the time we create it.
___
*[`relayer/coreum/contract.go` line 586 at r6](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/160#-Nt0pqb-1yuPimV_ru1g:-Nt0szujDiQHGAEjwZPX:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/73f26209d4c4492a8d379674597e76a66d6e415f/relayer/coreum/contract.go#L586)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Can't you simply put the body of `c.deployContract` here and use the exported method everywhere?
</blockquote></details>

Done.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/160)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by keyleu — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/160)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
