### PR TITLE
Print error in case XRPL tx scanning is failed and retry after timeout.

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

Print error in case XRPL tx scanning is failed and retry after timeout.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/202)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/202)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @masihyeganeh, @miladz68, and @wojtek-coreum)

___
*[`relayer/xrpl/scanner.go` line 139 at r1](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/202#-Nucg5Sa1EuHbIcao-kv:-Nucg5Sa1EuHbIcao-kw:b-tico7z) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/b1a0d74852a95796552578a2ac2fa1583ec8ae7a/relayer/xrpl/scanner.go#L139)):*
> ```Go
> 		// set minLedger to start with it in next iteration
> 		// even if the error was returned we still re-scan from the lastLedger
> 		if lastLedger != 0 {
> ```

I can see that you assign minLedger to -1 in some places
Is it ok that you compare it to 0 here ? maybe it should be `if lastLedger > 0` ?

For me it is not clear what is the logic behind -1 here

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/202)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @wojtek-coreum, and @ysv)

**Review by ysv — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/202)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh and @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/202)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh, @wojtek-coreum, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/202)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh and @wojtek-coreum)

**Pull request merged**
