### PR TITLE
Add trace sending CLI

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

Add trace sending CLI

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/204)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/204)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @masihyeganeh, @miladz68, and @wojtek-coreum)

___
*[`relayer/coreum/contract.go` line 1532 at r1](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/204#-NuyNVa_5a3bIZ992OZ1:-NuyNVa_5a3bIZ992OZ2:b3p0o0q) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/1945630acc25ef5e032b99c095ef1b04ece7737a/relayer/coreum/contract.go#L1532)):*
> ```Go
> 	}
> 
> 	operationIDs, err := c.getUsedOperationIDsForTx(ctx, tx.Height)
> ```

what if here you use PendingOperations query instead of AvailableTickets.

The flow:
1. query PendingOperations by `height-1` and by `height`
2. select all new operations (ones which exist in height but don't exist in heigh-1).
3. since PendingOperation of needed type contains CoreumToXRPLTransfer inside. You can compare if sender, recipient, currency and optionally amount matches values in your tx. This way you have 99.9% probability of finding 1 operation which you need. This approach is better than tickets IMO.
```
CoreumToXRPLTransfer {  
issuer: String,  
currency: String,  
amount: Uint128,  
max\_amount: Option<Uint128>,  
sender: Addr,  
recipient: String,  
}
```
4. PendingOperation also contains id. You can use this id same way to query txs by events. Here I have a question (why your id is just ticket_sequence while usually it is `{timestamp}-{ticket-sequence}` ?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/204)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`relayer/coreum/contract.go` line 1532 at r1](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/204#-NuyNVa_5a3bIZ992OZ1:-Nv0yjv27yIHnXlZDYAn:bn8167m) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/1945630acc25ef5e032b99c095ef1b04ece7737a/relayer/coreum/contract.go#L1532)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

what if here you use PendingOperations query instead of AvailableTickets.

The flow:
1. query PendingOperations by `height-1` and by `height`
2. select all new operations (ones which exist in height but don't exist in heigh-1).
3. since PendingOperation of needed type contains CoreumToXRPLTransfer inside. You can compare if sender, recipient, currency and optionally amount matches values in your tx. This way you have 99.9% probability of finding 1 operation which you need. This approach is better than tickets IMO.
```
CoreumToXRPLTransfer {  
issuer: String,  
currency: String,  
amount: Uint128,  
max\_amount: Option<Uint128>,  
sender: Addr,  
recipient: String,  
}
```
4. PendingOperation also contains id. You can use this id same way to query txs by events. Here I have a question (why your id is just ticket_sequence while usually it is `{timestamp}-{ticket-sequence}` ?
</blockquote></details>

Agree, updated.

**Review by miladz68 — APPROVED** [review]
> Reviewed 10 of 15 files at r1, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/204)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @wojtek-coreum, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 10 of 15 files at r1, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/204)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, and @wojtek-coreum)

___
*[`relayer/client/bridge.go` line 247 at r3](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/204#-NvBi9Sd8hVMb3F8v8Sq:-NvBi9Se6oNPn-uSemkn:b-oxkj63) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/b951ec9c7a051243997e7bcd212a337cad8cd4a2/relayer/client/bridge.go#L247)):*
> ```Go
> type XRPLToCoreumTracingInfo struct {
> 	XRPLTx        rippledata.TransactionWithMetaData
> 	CoreumTx      *sdk.TxResponse
> ```

nit: why do we have `*sdk.TxResponse` here and `sdk.TxResponse` non-pointer in `CoreumToXRPLTracingInfo` ? is there a specific reason ?



_Code quote:_
```Go
CoreumTx      *sdk.TxResponse
```
___
*[`relayer/cmd/cli/coreum_cli.go` line 1032 at r3](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/204#-NvBjBCyA8BFxqEdqwdn:-NvBjBCyA8BFxqEdqwdo:bsomms0) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/b951ec9c7a051243997e7bcd212a337cad8cd4a2/relayer/cmd/cli/coreum_cli.go#L1032)):*
> ```Go
> 				components.Log.Info(
> 					ctx,
> 					"Transfer is complete for XRPL txs.",
> ```

how do you handle the situation when you have multiple bridge msgs inside single tx ?
I would probably just return error in such case since it is not usual usage & frankly speaking I doubt if smn would do this



_Code quote:_
```Go
"Transfer is complete for XRPL txs.",
```
___
*[`relayer/coreum/contract.go` line 1889 at r3](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/204#-NvBlRjw1XkY7TWwDdT0:-NvBlRjw1XkY7TWwDdT1:b35sxrc) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/b951ec9c7a051243997e7bcd212a337cad8cd4a2/relayer/coreum/contract.go#L1889)):*
> ```Go
> 				return true
> 			}
> 			return false
> ```

nit: u can just put `return attr.Value == value` instead of these 4 lines



_Code quote:_
```Go
			if attr.Value == value {
				return true
			}
			return false
```

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/204)* status: all files reviewed, 2 unresolved discussions (waiting on @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`relayer/client/bridge.go` line 247 at r3](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/204#-NvBi9Sd8hVMb3F8v8Sq:-NvBtJ1cAIYIyYl9UOe2:bt5ic0f) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/b951ec9c7a051243997e7bcd212a337cad8cd4a2/relayer/client/bridge.go#L247)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit: why do we have `*sdk.TxResponse` here and `sdk.TxResponse` non-pointer in `CoreumToXRPLTracingInfo` ? is there a specific reason ?
</blockquote></details>

 `*` is for optional attributes
___
*[`relayer/cmd/cli/coreum_cli.go` line 1032 at r3](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/204#-NvBjBCyA8BFxqEdqwdn:-NvBtUTDARd7vG5AZ4Wh:b5eh5ff) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/b951ec9c7a051243997e7bcd212a337cad8cd4a2/relayer/cmd/cli/coreum_cli.go#L1032)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

how do you handle the situation when you have multiple bridge msgs inside single tx ?
I would probably just return error in such case since it is not usual usage & frankly speaking I doubt if smn would do this
</blockquote></details>

We handle it, since the event logs are grouped per message in the transaction, so one Coreum transaction can contain multiple XRPL transactions. And even an integration test for the CLI produces such a situation. 
___
*[`relayer/coreum/contract.go` line 1889 at r3](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/204#-NvBlRjw1XkY7TWwDdT0:-NvBu39f4uII6D_lLL5A:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/b951ec9c7a051243997e7bcd212a337cad8cd4a2/relayer/coreum/contract.go#L1889)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit: u can just put `return attr.Value == value` instead of these 4 lines
</blockquote></details>

Done

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/204)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh and @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/204)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh and @wojtek-coreum)

**Pull request merged**
