### PR TITLE
Integrate repeat_delay into failed processes

### PR DESCRIPTION
**Pull request by ysv**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/200)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/200)* status: 1 of 6 files reviewed, 3 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`relayer/runner/config.go` line 267 at r2](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/200#-NuNRm0e7QKEgyyIhU_Z:-NuNRm0e7QKEgyyIhU__:b-aje9yw) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/6d156a6f4313f3e5c11c3b5855521773faebeb9a/relayer/runner/config.go#L267)):*
> ```Go
> 	}
> 	// Set the default value if the value is not set because of an old config version which doesn't contain retry_delay.
> 	if config.Processes.RetryDelay == 0 {
> ```

I would propose to have 2 functions 

1) ReadConfigFromFile as is now
2) SetDefaults 

The `ReadConfig` combines both. Such an idea will help make the logic more visible. 
___
*[`relayer/runner/config_test.go` line 130 at r2](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/200#-NuNSQucD3Cih0qgs_In:-NuNSQucD3Cih0qgs_Io:b-axrhpm) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/6d156a6f4313f3e5c11c3b5855521773faebeb9a/relayer/runner/config_test.go#L130)):*
> ```Go
> 
> // the func returns the default config snapshot as string for v1.1.0 relayer version.
> func getV110DefaultConfigString() string {
> ```

IMO we shouldn't keep full old config with the version name, we can generate it instead, with `omitempty` and check that we will fill in the missing attributes. 
Also, you can have 2 tests or table tests instead of a double call of `t.Run(...)`.
___
*[`relayer/runner/runner.go` line 186 at r2](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/200#-NuNP74T2ZX7edTd_lDR:-NuNP74T2ZX7edTd_lDS:btu6d61) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/6d156a6f4313f3e5c11c3b5855521773faebeb9a/relayer/runner/runner.go#L186)):*
> ```Go
> 		for {
> 			// start process and handle the panic
> ```

nit: we don't need that empty line IMO
___
*[`relayer/runner/runner_test.go` line 20 at r2](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/200#-NuNRKpT3WflVGXKkVPd:-NuNRKpT3WflVGXKkVPe:b-ibkr) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/6d156a6f4313f3e5c11c3b5855521773faebeb9a/relayer/runner/runner_test.go#L20)):*
> ```Go
> 
> type counter struct {
> 	mu *sync.RWMutex
> ```

Can't you use `atomic.Int64` instead?

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/200)* status: 1 of 6 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`relayer/runner/config.go` line 267 at r2](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/200#-NuNRm0e7QKEgyyIhU_Z:-NuORNK35MOk2nhIgxsL:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/6d156a6f4313f3e5c11c3b5855521773faebeb9a/relayer/runner/config.go#L267)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I would propose to have 2 functions 

1) ReadConfigFromFile as is now
2) SetDefaults 

The `ReadConfig` combines both. Such an idea will help make the logic more visible.
</blockquote></details>

Done.
___
*[`relayer/runner/config_test.go` line 130 at r2](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/200#-NuNSQucD3Cih0qgs_In:-NuOV_Me6yfqM5BcNkP9:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/6d156a6f4313f3e5c11c3b5855521773faebeb9a/relayer/runner/config_test.go#L130)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO we shouldn't keep full old config with the version name, we can generate it instead, with `omitempty` and check that we will fill in the missing attributes. 
Also, you can have 2 tests or table tests instead of a double call of `t.Run(...)`.
</blockquote></details>

Done.
___
*[`relayer/runner/runner_test.go` line 20 at r2](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/200#-NuNRKpT3WflVGXKkVPd:-NuOWWHj1um-uFWW0YZ-:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/6d156a6f4313f3e5c11c3b5855521773faebeb9a/relayer/runner/runner_test.go#L20)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Can't you use `atomic.Int64` instead?
</blockquote></details>

Done.

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 2 of 6 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/200)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil and @miladz68)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/200)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

___
*[`relayer/runner/config_test.go` line 40 at r3](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/200#-NuT7ZTI3NhsBClOAeJG:-NuT7ZTI3NhsBClOAeJH:b-rp3ry9) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/21682e794c58d914bd09c5c7a5b6cccdf2291ba5/relayer/runner/config_test.go#L40)):*
> ```Go
> 		},
> 		{
> 			name: "zero retry_delay", // version 1.1.0 or earlier.
> ```

nit: use `_` between words for table test names, because if you don't provide it the go will add in the output anyway, so to find a failed test better to have the same names in the code and output

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/200)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @miladz68 and @wojtek-coreum)

___
*[`relayer/runner/config_test.go` line 40 at r3](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/200#-NuT7ZTI3NhsBClOAeJG:-NuTELNB3w-eM2RHYGA0:bb7f2mf) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/21682e794c58d914bd09c5c7a5b6cccdf2291ba5/relayer/runner/config_test.go#L40)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

nit: use `_` between words for table test names, because if you don't provide it the go will add in the output anyway, so to find a failed test better to have the same names in the code and output
</blockquote></details>

done

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/200)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @miladz68 and @wojtek-coreum)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/200)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
