### PR TITLE
Update the spec by adding the correct owner actions definition.

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

Update the spec by adding the correct owner actions definition.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/195)

### CODE REVIEW

**Review by keyleu — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/195)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`spec/spec.md` line 20 at r1](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/195#-Nsn3nMuE4Ck8vlMPbLx:-Nsn3nMv9qZe-PuLIRoi:b-molks3) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/0aae36e26ea2c7d364dfd0b2238cbabfb678d4bd/spec/spec.md#L20)):*
> ```Markdown
> The bridge contract is the major state transition of the bridge. It holds the operations state and protects the
> execution using the trusted addresses voting/signing mechanisms. Also, it has an owner account that can change the
> settings of the contract or request operation execution from the relayers.
> ```

Maybe settings of the tokens instead of settings of the contracts? wdyt?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/195)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu, @miladz68, @wojtek-coreum, and @ysv)

___
*[`spec/spec.md` line 20 at r1](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/195#-Nsn3nMuE4Ck8vlMPbLx:-Nsn4_YX9RpCkAPvEwN6:b-wn2awd) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/0aae36e26ea2c7d364dfd0b2238cbabfb678d4bd/spec/spec.md#L20)):*
<details><summary><i>Previously, keyleu (Keyne) wrote…</i></summary><blockquote>

Maybe settings of the tokens instead of settings of the contracts? wdyt?
</blockquote></details>

Actually both.

**Review by keyleu — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/195)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by keyleu — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/195)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Pull request merged**
