### PR TITLE
Add admin actions stress test

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

* Refactor stress tests to make them more maintainable
* Add admin actions stress test

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/199)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/199)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/stress/env_test.go` line 58 at r1](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/199#-NtWimBV6j-Kb-gZLpG3:-NtWimBW2bRHlHBO5E2m:b-yex7us) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/9c2bfe0705498d38a61d2a90f6ece1b29b75555e/integration-tests/stress/env_test.go#L58)):*
> ```Go
> 	ContractOwner  sdk.AccAddress
> 	BridgeClient   *bridgeclient.BridgeClient
> 	ContractClient *coreum.ContractClient
> ```

I can see that ContractClient is part of BridgeClient just this field is private. Maybe bridge client here is enough & we can expose contract client from it ?

Also I like that inside BridgeClient we use interface but here it is struct



_Code quote:_
```Go
ContractClient *coreum.ContractClient
```
___
*[`integration-tests/stress/env_test.go` line 313 at r1](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/199#-NtWgkAH-tM81Q9G4c17:-NtWgkAH-tM81Q9G4c18:b-cbwspw) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/9c2bfe0705498d38a61d2a90f6ece1b29b75555e/integration-tests/stress/env_test.go#L313)):*
> ```Go
> 
> // RepeatOwnerActionWithDelay calls the action, waits for some time and call the actionCompensation.
> func (env *Env) RepeatOwnerActionWithDelay(ctx context.Context, action, actionCompensation func() error) error {
> ```

nit: rollbackAction is better name IMO



_Code quote:_
```Go
actionCompensation
```
___
*[`integration-tests/stress/stress_test.go` line 341 at r1](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/199#-NtWi1Yo7bL16hYUpwp7:-NtWi1Yo7bL16hYUpwp8:b28fszo) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/9c2bfe0705498d38a61d2a90f6ece1b29b75555e/integration-tests/stress/stress_test.go#L341)):*
> ```Go
> 				ctx,
> 				env.ContractOwner,
> 				// low base XRPL fee, so the XRPL transactions won't pass
> ```

nit: this is the normal fee, right ?

update comment ?



_Code quote:_
```Go
// low base XRPL fee, so the XRPL transactions won't pass
```

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/199)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/stress/env_test.go` line 58 at r1](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/199#-NtWimBV6j-Kb-gZLpG3:-NuNMbSeCpmqnl2KYVsf:ba4srd) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/9c2bfe0705498d38a61d2a90f6ece1b29b75555e/integration-tests/stress/env_test.go#L58)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I can see that ContractClient is part of BridgeClient just this field is private. Maybe bridge client here is enough & we can expose contract client from it ?

Also I like that inside BridgeClient we use interface but here it is struct
</blockquote></details>

IMO we shouldn't, we have both here since the BridgeClient is more limited, and the ContractClient is its dependency, so it shouldn't be exportable. 
Also, we don't need the interface here, since it's a test, so we won't need to mock it or have multiple implementations. 
___
*[`integration-tests/stress/env_test.go` line 313 at r1](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/199#-NtWgkAH-tM81Q9G4c17:-NuNNRRr-Lhn2_9uTde6:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/9c2bfe0705498d38a61d2a90f6ece1b29b75555e/integration-tests/stress/env_test.go#L313)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit: rollbackAction is better name IMO
</blockquote></details>

Done
___
*[`integration-tests/stress/stress_test.go` line 341 at r1](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/199#-NtWi1Yo7bL16hYUpwp7:-NuNNa0-Efpi6kwA1lwR:b-bu91xm) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/9c2bfe0705498d38a61d2a90f6ece1b29b75555e/integration-tests/stress/stress_test.go#L341)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit: this is the normal fee, right ?

update comment ?
</blockquote></details>

Updated

**Review by ysv — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/199)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @wojtek-coreum)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/199)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @wojtek-coreum)

___
*[`integration-tests/stress/env_test.go` line 315 at r2](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/199#-NuY5NRGD1p1CvYT5Gdm:-NuZNgpNE1EYXHBwzzqU:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/db6115befda3a05cbb43cf384c78feaa262157ce/integration-tests/stress/env_test.go#L315)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

do `defer cancel()` here, instead of separate calls everywhere
</blockquote></details>

Done.

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/199)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @wojtek-coreum)

___
*[`integration-tests/stress/env_test.go` line 315 at r2](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/199#-NuY5NRGD1p1CvYT5Gdm:-Nucgp4e0bGIwCoKZ0LK:b-fqxsfg) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/db6115befda3a05cbb43cf384c78feaa262157ce/integration-tests/stress/env_test.go#L315)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I would prefer to move this to a separate func

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/199)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @wojtek-coreum)

___
*[`integration-tests/stress/env_test.go` line 315 at r2](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/199#-NuY5NRGD1p1CvYT5Gdm:-Nucqrn071UJQnyfXPCV:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/db6115befda3a05cbb43cf384c78feaa262157ce/integration-tests/stress/env_test.go#L315)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I would prefer to move this to a separate func
</blockquote></details>

Done.

**Review by miladz68 — APPROVED** [review]
> Reviewed 5 of 7 files at r1, 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/199)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum)

**Review by ysv — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/199)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/199)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/199)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/199)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil)

**Pull request merged**
