### PR TITLE
Add relayer version metric + dashboard.

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

Add relayer version metric + dashboard.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/205)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/205)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @masihyeganeh, @miladz68, and @wojtek-coreum)

___
*[`infra/composer/grafana/dashboards/relayer.json` line 1721 at r1](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/205#-NvBpOOnDnj7h87qbtWV:-NvBpOOnDnj7h87qbtWW:b-ztaqb) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/7c13cef303e35a7663c5d6e089895e82d3e75bc8/infra/composer/grafana/dashboards/relayer.json#L1721)):*
> ```JSON
>           "selected": true,
>           "text": [
>             "devcore1l9d79mawwv2lhel5eh9z0mp0fpff7pz7grm5tm"
> ```

are these hardcoded values expected here ?

I think Artem will just copy these

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/205)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`infra/composer/grafana/dashboards/relayer.json` line 1721 at r1](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/205#-NvBpOOnDnj7h87qbtWV:-NvBxJAy01tzDeorghor:b-v6s1o3) ([raw file](https://github.com/CoreumFoundation/coreumbridge-xrpl/blob/7c13cef303e35a7663c5d6e089895e82d3e75bc8/infra/composer/grafana/dashboards/relayer.json#L1721)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

are these hardcoded values expected here ?

I think Artem will just copy these
</blockquote></details>

Removed.

**Review by ysv — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/205)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh, @miladz68, and @wojtek-coreum)

**Review by miladz68 — DISMISSED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/205)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh and @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreumbridge-xrpl/205)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh and @wojtek-coreum)

**Review by ysv — APPROVED** [review]

**Pull request merged**
